### ISSUE TITLE
Error in cap1xxx.py

### ISSUE THREAD

**Issue by AndiCui** [pimoroni/explorer-hat#18]
```
pi@raspberrypi:~/explorer-hat/examples$ python test.py 

This basic example tests the various functions of Explorer HAT,
touching any of the buttons should output a message, lights should pulse
and analog/digital values should be read every second.

Press CTRL+C to exit.

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    import explorerhat
  File "build/bdist.linux-armv6l/egg/explorerhat.py", line 692, in <module>
    _cap1208 = Cap1208()
  File "/usr/local/lib/python2.7/dist-packages/cap1xxx.py", line 275, in __init__
    raise Exception("Product ID {} not supported!".format(self.product_id))
Exception: Product ID 0 not supported!
```

on latest raspbian

**Comment by Gadgetoid** [comment]
This would appear to be a communications failure with the Captouch chip, I don't believe it's a bug in the code. If it persists, it's possibly a hardware fault worth discussing on the forums.
