### ISSUE TITLE
Setup doesn't enable i2c on bullseye

### ISSUE THREAD

**Issue by bjoernbusch** [pimoroni/explorer-hat#51]
I followed the instructions to install the explorer library, but the first script didn't run with a python error:

```pi@zeropi:~ $ python script.py 
Traceback (most recent call last):
  File "/home/pi/script.py", line 5, in <module>
    import explorerhat as eh
  File "/usr/lib/python3/dist-packages/explorerhat/__init__.py", line 28, in <module>
    from .ads1015 import read_se_adc, adc_available
  File "/usr/lib/python3/dist-packages/explorerhat/ads1015.py", line 22, in <module>
    i2c = SMBus(i2c_bus_id())
FileNotFoundError: [Errno 2] No such file or directory
```

I check whether something would be detected:

```
pi@zeropi:~ $ i2cdetect -y 1
Error: Could not open file `/dev/i2c-1' or `/dev/i2c/1': No such file or directory
```

So I enabled i2c via raspi-config and then everything worked.

--> The setup scripts should be updated.

**Comment by Gadgetoid** [comment]
I believe this has since been fixed. The i2c/spi enable scripts, among others, were blocking bullseye and silently failing.
